server:
  port: 8000
spring:
  application:
    name: eureka-client

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka1.wft.com:7001/eureka/,http://eureka2.wft.com:7002/eureka/
